USE [master]
GO

/****** Object:  Database [CHUNGKHOAN]    Script Date: 4/26/2022 5:10:37 PM ******/
CREATE DATABASE [CHUNGKHOAN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CHUNGKHOAN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SERVER0\MSSQL\DATA\CHUNGKHOAN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CHUNGKHOAN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SERVER0\MSSQL\DATA\CHUNGKHOAN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHUNGKHOAN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CHUNGKHOAN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET ARITHABORT OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CHUNGKHOAN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CHUNGKHOAN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CHUNGKHOAN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CHUNGKHOAN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET RECOVERY FULL 
GO

ALTER DATABASE [CHUNGKHOAN] SET  MULTI_USER 
GO

ALTER DATABASE [CHUNGKHOAN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CHUNGKHOAN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CHUNGKHOAN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CHUNGKHOAN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CHUNGKHOAN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CHUNGKHOAN] SET QUERY_STORE = OFF
GO

USE [CHUNGKHOAN]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CHUNGKHOAN] SET  READ_WRITE 
GO

